# Generated by Django 6.0.2 on 2026-04-09 13:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_sale', models.DateTimeField(auto_now_add=True, verbose_name='Sale Time')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Cashier')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SaleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Sold')),
                ('price_at_sale', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the product at the moment of sale', max_digits=9, null=True, verbose_name='Unit Price at Sale')),
                ('total_price_row', models.DecimalField(blank=True, decimal_places=2, help_text='Total price of the current article', max_digits=9, null=True, verbose_name='Total price')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleattributes', verbose_name='Sale Reference')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_items', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sales Items',
            },
        ),
    ]
