# Generated by Django 6.0.2 on 2026-02-18 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_sale', models.DateTimeField(auto_now_add=True, verbose_name='Sale Time')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='accounts.employee', verbose_name='Cashier')),
            ],
            options={
                'verbose_name': 'Sale Attribute',
                'verbose_name_plural': 'Sale Attributes',
            },
        ),
        migrations.CreateModel(
            name='SaleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Sold')),
                ('price_at_sale', models.DecimalField(decimal_places=2, help_text='Price of the product at the moment of sale', max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Unit Price at Sale')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleattributes', verbose_name='Sale Reference')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_items', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Sale Item',
                'verbose_name_plural': 'Sales Items',
            },
        ),
    ]
