# Generated by Django 6.0.2 on 2026-02-14 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0002_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_sale', models.DateTimeField(auto_now_add=True)),
                ('cacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='SaleItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_quantity', models.PositiveIntegerField(default=1)),
                ('price_at_sale', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.saleattributes')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sold_items', to='products.product')),
            ],
        ),
    ]
