# Generated by Django 6.0.2 on 2026-02-26 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_saleattributes_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitems',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total amount to be paid', max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Total amount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleitems',
            name='total_price_row',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total price of the current article', max_digits=9, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Total price'),
            preserve_default=False,
        ),
    ]
