# Generated by Django 6.0.2 on 2026-02-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitems_total_amount_saleitems_total_price_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount to be paid', max_digits=12, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='saleitems',
            name='total_price_row',
            field=models.DecimalField(decimal_places=2, help_text='Total price of the current article', max_digits=9, verbose_name='Total price'),
        ),
    ]
