# Generated by Django 6.0.2 on 2026-02-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_saleitems_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='total_price_row',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price of the current article', max_digits=9, verbose_name='Total price'),
        ),
    ]
