# Generated by Django 6.0.2 on 2026-02-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_saleitems_total_price_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount to be paid', max_digits=12, verbose_name='Total amount'),
        ),
    ]
