# Generated by Django 6.0.2 on 2026-02-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_saleitems_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitems',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount to be paid', max_digits=12, null=True, verbose_name='Total amount'),
        ),
        migrations.AlterField(
            model_name='saleitems',
            name='total_price_row',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total price of the current article', max_digits=9, null=True, verbose_name='Total price'),
        ),
    ]
