# Generated by Django 6.0.2 on 2026-02-28 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_saleitems_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saleitems',
            name='total_amount',
        ),
    ]
