# Generated by Django 6.0.2 on 2026-03-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_saleitems_total_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleattributes',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterField(
            model_name='saleitems',
            name='price_at_sale',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price of the product at the moment of sale', max_digits=9, null=True, verbose_name='Unit Price at Sale'),
        ),
    ]
