# Generated by Django 6.0.2 on 2026-04-12 20:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_alter_product_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAttributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_delivery', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Delivery Time')),
                ('document_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('DELIVERY_NOTE', 'Delivery Note')], verbose_name='Document Type')),
                ('document_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Document Number')),
                ('document_date', models.DateField(verbose_name='Document Date')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
        migrations.CreateModel(
            name='DeliveryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity Delivered')),
                ('price_at_delivery', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the product at the moment of delivery', max_digits=9, null=True, verbose_name='Unit Price at Delivery')),
                ('total_price_row', models.DecimalField(blank=True, decimal_places=2, help_text='Total price of the current article', max_digits=9, null=True, verbose_name='Total price')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deliveries.deliveryattributes', verbose_name='Delivery Reference')),
                ('delivery_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivered_items', to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Delivery Item',
                'verbose_name_plural': 'Delivery Items',
            },
        ),
    ]
