# Generated by Django 6.0.2 on 2026-04-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
        ('products', '0002_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryattributes',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='products.suppliers', verbose_name='Supplier'),
            preserve_default=False,
        ),
    ]
