# Generated by Django 6.0.2 on 2026-02-18 17:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='product name')),
                ('delivery_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='delivery price')),
                ('sell_price', models.DecimalField(blank=True, decimal_places=2, help_text='Selling price per unit', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='sale price')),
                ('quantity', models.IntegerField(default=0, help_text='Can be negative if items are sold before delivery is recorded', verbose_name='stock quantity')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, help_text='Scan the barcode or enter the EAN-13 number', max_length=13, null=True, verbose_name='Barcode number')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcode', to='products.product', verbose_name='Linked Product')),
            ],
            options={
                'verbose_name': 'Barcode',
                'verbose_name_plural': 'Barcodes',
            },
        ),
    ]
