# Generated by Django 6.0.2 on 2026-04-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, help_text='Can be negative if items are sold before delivery is recorded', verbose_name='stock quantity'),
        ),
    ]
