# Generated by Django 6.0.2 on 2026-03-05 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('bulstat', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_vat', message='VAT must contain only digits', regex='^\\d+$')])),
                ('vat_n', models.CharField(blank=True, max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_vat', message='VAT must contain only digits', regex='^BG\\d+$')])),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.suppliers'),
        ),
    ]
