# Generated by Django 6.0.2 on 2026-03-05 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_suppliers_product_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='bulstat',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_vat', message='VAT must contain only digits', regex='^\\d+$')], verbose_name='BULSTAT'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='vat_n',
            field=models.CharField(blank=True, help_text='Only if the company is VAT registered!', max_length=14, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_vat', message='VAT must contain only digits', regex='^BG\\d+$')], verbose_name='VAT:'),
        ),
    ]
