# Generated by Django 6.0.2 on 2026-03-05 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_suppliers_bulstat_alter_suppliers_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='vat_n',
            field=models.CharField(blank=True, help_text='Only if the company is VAT registered!', max_length=14, validators=[django.core.validators.RegexValidator(code='invalid_vat', message='VAT must contain only digits', regex='^BG\\d+$')], verbose_name='VAT:'),
        ),
    ]
