# Generated by Django 6.0.2 on 2026-03-11 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_suppliers_vat_n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['internal_code'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
