# Generated by Django 6.0.2 on 2026-02-18 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('phone', models.CharField(blank=True, max_length=10, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Cashier', 'Cashier'), ('Warehouse', 'Warehouse')], default='Cashier', max_length=9)),
                ('password', models.CharField(default='1234', help_text='Enter password, digits only', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password must contain only digits.', regex='^\\d+$')])),
            ],
        ),
    ]
