# Generated by Django 6.0.2 on 2026-02-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('Manager', 'Manager'), ('Cashier', 'Cashier'), ('Warehouse', 'Warehouse')], default='Cashier', max_length=9)),
                ('password', models.CharField(max_length=12, unique=True)),
            ],
        ),
    ]
